import type { ConversationInput, ToolCall } from '../task/conversation_types.js';
import type { TaskInput } from '../task/task_types.js';
import type { EncodedTensor, LlmStagePayload, StagePayload } from './stage_payload_types.js';

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
//	StagePayloadFactory — builds the value a pipeline stage starts from
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

/**
 * Builds the `StagePayload` values carried by `stage.assign`/`stage.result` messages, so
 * cli.ts, stage_helper_llm_qwen3_0_6b_sharded.ts, stage_helper_llm_gemma_nano_chrome_full.ts, and
 * stage_helper_llm_qwen3_5_0_8b_full.ts share one definition of each payload shape instead of
 * repeating the object literals inline.
 */
export class StagePayloadFactory {
	/**
	 * Builds the value handed to the first stage of a task, from the task input the consumer
	 * submitted.
	 *
	 * Every task type is answered here, so the gateway never decides what a first stage
	 * value looks like for itself. Adding a task type is a change to this one method rather
	 * than to each place the gateway starts or restarts a task.
	 *
	 * @param input The task type and value the consumer submitted.
	 * @returns The stage payload to assign to the task's first stage.
	 */
	static initial(input: TaskInput): StagePayload {
		if (input.taskType === 'task_type_dev_formula') return StagePayloadFactory.formula(input.input);
		if (typeof input.input === 'string') return StagePayloadFactory.llmPrompt(input.input);
		return StagePayloadFactory.llmConversation(input.input);
	}

	/**
	 * Builds the payload for a formula stage: the plain number, unchanged.
	 *
	 * @param value The numeric value produced by or fed into a formula stage.
	 * @returns The stage payload to send in a `stage.assign` or `stage.result` message.
	 */
	static formula(value: number): StagePayload {
		return value;
	}

	/**
	 * Builds the initial LLM stage payload for `stage_llm_qwen3_0_6b_shard1of3`'s first round, carrying
	 * the submitted prompt text.
	 *
	 * @param prompt The prompt text submitted for the task.
	 * @returns The stage payload to assign to `stage_llm_qwen3_0_6b_shard1of3`.
	 */
	static llmPrompt(prompt: string): LlmStagePayload {
		return { text: prompt };
	}

	/**
	 * Builds the initial LLM stage payload for a task submitted with a whole conversation rather
	 * than with one prompt, carrying that conversation for the stage helper to hand to its model's
	 * chat template.
	 *
	 * @param conversation The conversation submitted for the task.
	 * @returns The stage payload to assign to the task's first stage.
	 */
	static llmConversation(conversation: ConversationInput): LlmStagePayload {
		return { conversation };
	}

	/**
	 * Builds the hand-off payload passed from one shard to the next within the same
	 * generation round: the shard's boundary tensors, plus the token identifiers and
	 * position the receiving shard needs to build its own feeds.
	 *
	 * @param tensors The encoded boundary tensors produced by the shard that just ran.
	 * @param inputIds The token identifiers processed in this round.
	 * @param position The position of the first token in `inputIds` within the full sequence.
	 * @param promptTokenCount The exact number of tokens the prompt was encoded into, captured by
	 * the first shard's first round and carried forward on every hand-off since, because each
	 * shard runs on its own device with its own separate memory. See milestone 3 of
	 * [issue #150](https://github.com/webai-at-home/webai-at-home/issues/150).
	 * @returns The stage payload to assign to the next shard in the round.
	 */
	static llmHandoff(tensors: Record<string, EncodedTensor>, inputIds: number[], position: number, promptTokenCount?: number): LlmStagePayload {
		const payload: LlmStagePayload = { tensors, inputIds, position };
		if (promptTokenCount !== undefined) {
			payload.promptTokenCount = promptTokenCount;
		}
		return payload;
	}

	/**
	 * Builds the payload the final shard returns to continue generation for another round.
	 *
	 * It carries what this round produced and not the answer so far, so the payload stays the
	 * same size whether it is the first round or the hundredth.
	 *
	 * @param newText The text this round produced, beyond everything the rounds before it produced.
	 * @param nextTokenId The token identifier generated by this round, to feed as the next round's input.
	 * @param position The position `nextTokenId` occupies within the full sequence.
	 * @param promptTokenCount The exact number of tokens the prompt was encoded into, carried
	 * forward so the round it loops back to can hand it to the next shard again. See milestone 3
	 * of [issue #150](https://github.com/webai-at-home/webai-at-home/issues/150).
	 * @returns The stage payload that loops back to `stage_llm_qwen3_0_6b_shard1of3`.
	 */
	static llmContinue(newText: string, nextTokenId: number, position: number, promptTokenCount?: number): LlmStagePayload {
		const payload: LlmStagePayload = { ...StagePayloadFactory.piece(newText), inputIds: [nextTokenId], position, done: false };
		if (promptTokenCount !== undefined) {
			payload.promptTokenCount = promptTokenCount;
		}
		return payload;
	}

	/**
	 * Builds the payload a stage returns to continue a generation it is holding open in the
	 * memory of the device running it.
	 *
	 * The Chrome built-in language-model task uses this when the consumer asked for its answer
	 * in pieces: one stage run reads one piece from a stream the same device keeps open, so the
	 * payload carries that piece and says the generation is already under way.
	 *
	 * @param newText The piece this run read, beyond everything the runs before it read.
	 * @returns The stage payload that runs the same stage again on the same device.
	 */
	static llmPartialText(newText: string): LlmStagePayload {
		return { ...StagePayloadFactory.piece(newText), isContinuation: true, done: false };
	}

	/**
	 * Builds the payload a stage returns once generation is complete.
	 *
	 * This is the one result that carries the whole answer. It is what the gateway stores as
	 * the task result, so a consumer that wants the answer as one piece of text never has to
	 * join anything, and a consumer that has been joining the pieces can check what it built
	 * against what the device that generated it actually produced.
	 *
	 * @param text The complete generated text.
	 * @param newText The text the run that finished the answer produced, when that run produced
	 * any. Left out by a run that produced the whole answer by itself, since there were no
	 * earlier pieces for this to be measured against.
	 * @param usage The token counts and the reason generation stopped, when the worker's engine
	 * can report them. Left out entirely by a worker whose engine cannot, per milestone 2 of
	 * [issue #150](https://github.com/webai-at-home/webai-at-home/issues/150) — a worker is added
	 * to this in milestone 3, one engine at a time, rather than every worker gaining it at once.
	 * @returns The stage payload that ends the task's generation loop.
	 */
	static llmDone(
		text: string,
		newText?: string,
		usage?: { promptTokenCount?: number; completionTokenCount?: number; stopReason?: 'end_of_sequence' | 'max_new_tokens' | 'interrupted' },
	): LlmStagePayload {
		const payload: LlmStagePayload = { text, ...StagePayloadFactory.piece(newText), done: true };
		if (usage?.promptTokenCount !== undefined) {
			payload.promptTokenCount = usage.promptTokenCount;
		}
		if (usage?.completionTokenCount !== undefined) {
			payload.completionTokenCount = usage.completionTokenCount;
		}
		if (usage?.stopReason !== undefined) {
			payload.stopReason = usage.stopReason;
		}
		return payload;
	}

	/**
	 * Builds the payload a stage returns once the model has asked for a tool instead of writing an
	 * answer.
	 *
	 * This ends the task exactly as {@link llmDone} does, and carries no answer text, because there
	 * is none: a model that asks for a tool writes nothing else. The empty `text` is what says so,
	 * rather than the field being left out, so that every reader of a finished task's result can go
	 * on reading `text` without first checking which of the two kinds of ending it received.
	 *
	 * @param toolCalls The tools the model asked to have called, in the order it asked for them.
	 * @param usage The token counts and the reason generation stopped, when the worker's engine can
	 * report them. A worker that stopped generating as soon as a complete tool call had been written
	 * reports `interrupted`, which is what it did.
	 * @returns The stage payload that ends the task with a request to call a tool.
	 * @throws {Error} If no tool call is given, since a result that asks for no tool and carries no
	 * answer says nothing at all.
	 */
	static llmToolCalls(
		toolCalls: ToolCall[],
		usage?: { promptTokenCount?: number; completionTokenCount?: number; stopReason?: 'end_of_sequence' | 'max_new_tokens' | 'interrupted' },
	): LlmStagePayload {
		if (toolCalls.length === 0) {
			throw new Error('A stage result that asks for no tool and carries no answer text says nothing at all.');
		}
		const payload: LlmStagePayload = { text: '', toolCalls, done: true };
		if (usage?.promptTokenCount !== undefined) {
			payload.promptTokenCount = usage.promptTokenCount;
		}
		if (usage?.completionTokenCount !== undefined) {
			payload.completionTokenCount = usage.completionTokenCount;
		}
		if (usage?.stopReason !== undefined) {
			payload.stopReason = usage.stopReason;
		}
		return payload;
	}

	/**
	 * States what a run produced, or says nothing when it produced nothing.
	 *
	 * A run that reports an empty piece and a run that reports no piece are saying the same
	 * thing, so only one of the two is ever sent. Every payload builder above goes through this,
	 * which is what saves each of them, and every reader of a payload, from checking for both.
	 *
	 * @param newText The text a run produced, if any.
	 * @returns The piece to spread into a payload, which is nothing at all when there is none.
	 */
	private static piece(newText: string | undefined): { newText?: string } {
		return newText === undefined || newText === '' ? {} : { newText };
	}
}
